version: '3.3'
services:
  strapi-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'strapi'
      MYSQL_USER: 'strapi'
      MYSQL_PASSWORD: 'strapi'
      MYSQL_ROOT_PASSWORD: 'strapi'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - strapi_db:/var/lib/mysql
volumes:
  strapi_db:
